FROM rust:buster as build
RUN apt-get update
#RUN apk add --no-cache musl-dev tzdata perl gcc g++ make libffi-dev libtool autoconf automake curl gcc-arm-none-eabi
RUN apt-get install -y musl-dev build-essential libtool libffi-dev make autoconf automake curl

RUN mkdir /app
WORKDIR /app

RUN echo "RUST VERSION --- $(rustc -V)"

RUN cargo init ./ --bin --edition 2018

COPY ./Cargo.lock /app/Cargo.lock
COPY ./Cargo.toml /app/Cargo.toml

#RUN rustup target add armv7-unknown-linux-musleabihf

RUN cargo build --release --verbose --target-dir "/app/dist" --features vendored
#RUN cargo build --target=armv7-unknown-linux-musleabihf --release --verbose --target-dir "/app/dist" --features vendored

RUN rm src/*.rs

COPY ./src /app/src


RUN rm /app/dist/release/deps/simple_deployer*
RUN cargo build --release --verbose --target-dir "/app/dist" --features vendored && ls /app/dist/ && mv /app/dist/release/simple-deployer /app/entrypoint && rm -rf /app/dist/

# our final base
FROM rust:buster

RUN mkdir /app
WORKDIR /app

# copy the build artifact from the build stage
COPY --from=build /app/entrypoint .

ENTRYPOINT [ "/app/entrypoint" ]
