FROM ubuntu:21.10 as build

# Update default packages
#RUN  sed -i 's/http:\/\//https:\/\//g' /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    curl libssl-dev musl-dev tzdata perl gcc g++ make libffi-dev libtool autoconf automake

# Update new packages
RUN apt-get update

# Get Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc

RUN mkdir /app
WORKDIR /app

RUN echo "RUST VERSION --- $(rustc -V)"

RUN cargo init ./ --bin --edition 2018

COPY ./Cargo.lock /app/Cargo.lock
COPY ./Cargo.toml /app/Cargo.toml

RUN cargo build --release --verbose --target-dir "/app/dist" --features vendored
RUN rm src/*.rs

COPY ./src /app/src

RUN rm /app/dist/release/deps/simple_deployer*
RUN cargo build --release --verbose --target-dir "/app/dist" --features vendored && mv /app/dist/release/simple-deployer /app/entrypoint && rm -rf /app/dist/

# our final base
FROM rust:buster

RUN mkdir /app
WORKDIR /app

# copy the build artifact from the build stage
COPY --from=build /app/entrypoint .

ENTRYPOINT [ "/app/entrypoint" ]
