name: AUTO DEPLOYMENT

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      -
        name: SETUP QEMUX
        uses: docker/setup-qemu-action@v1
      -
        name: SET UP DOCKERX
        uses: docker/setup-buildx-action@v1
      -
        name: LOGIN TO DOCKERHUB
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        id: extract_version
        name: Get Version From Cargo.toml
        run: echo "::set-output name=version::$(awk -F'[ ="]+' '$1 == "version" { print $2 }' Cargo.toml)"
      -
        name: Build Docker and Push to Docker SimpleDeploy REPO
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
          tags: |
            shellcodesniper/simpledeploy:stable
            shellcodesniper/simpledeploy:v${{ steps.extract_version.outputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache-simple
          cache-to: type=local,dest=/tmp/.buildx-cache-new-simple,mode=max
      - 
        name: MAKE RELEASE DATE
        id: date
        run: echo "release_time=$(TZ=Asia/Seoul date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
      - 
        name: CREATE RELEASE
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          release_name: Release v${{ steps.extract_version.outputs.version }} [${{ env.release_time }}]
          body: AUTO RELEASE MADE FROM workflows
          draft: true
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-simple /tmp/.buildx-cache-simple
      -
        name: SSH BUILD!
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/opc/SimpleDeployer
            git stash
            git pull
            ./bin/build_for_arm.sh
          host: ${{ secrets.SSH_HOST }}
          user: opc
          key: ${{ secrets.PRIVATE_KEY}}
