name: AUTO Develop Version DEPLOYMENT

on:
  push:
    branches: [ develop ]

jobs:
  build_and_deploy:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      -
        name: SETUP QEMUX
        uses: docker/setup-qemu-action@v1
      -
        name: SET UP DOCKERX
        uses: docker/setup-buildx-action@v1
      -
        name: LOGIN TO DOCKERHUB
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        id: extract_version
        name: Get Version From Cargo.toml
        run: echo "::set-output name=version::$(awk -F'[ ="]+' '$1 == "version" { print $2 }' Cargo.toml)"
      -
        name: Build Docker and Push to Docker SimpleDeploy REPO
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
          tags: |
            shellcodesniper/simpledeploy:latest
            shellcodesniper/simpledeploy:dev-v${{ steps.extract_version.outputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache-simple-latest
          cache-to: type=local,dest=/tmp/.buildx-cache-new-simple-latest,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-simple-latest
          mv /tmp/.buildx-cache-new-simple-latest /tmp/.buildx-cache-simple-latest